import {isRateLimited} from '../lib/cache.js';
const CACHE=new Map(),TTL=3*60*60*1000,MAX=300,H={'User-Agent':'Mozilla/5.0','Accept':'application/json','Referer':'https://finance.yahoo.com/'};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function cors(res){res.setHeader('Access-Control-Allow-Origin',process.env.ALLOWED_ORIGIN||'*');res.setHeader('Access-Control-Allow-Methods','POST, OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type');res.setHeader('Cache-Control','no-store')}
function send(res,s,b){cors(res);return res.status(s).json(b)}
function ticker(v){const x=String(v||'').trim().toUpperCase();if(!x||!/^[A-Z0-9._&-]{1,25}$/.test(x))return'';return x.endsWith('.NS')||x.endsWith('.BO')||x.startsWith('^')?x:x+'.NS'}
function get(k){const x=CACHE.get(k);if(!x||Date.now()>x.e){CACHE.delete(k);return null}return x.d}function set(k,d){if(CACHE.size>=MAX)CACHE.delete(CACHE.keys().next().value);CACHE.set(k,{d,e:Date.now()+TTL})}
async function yf(url,tries=2){let last;for(let i=1;i<=tries;i++){const c=new AbortController(),t=setTimeout(()=>c.abort(),15000);try{const r=await fetch(url,{headers:H,signal:c.signal}),txt=await r.text();clearTimeout(t);if(r.status===429||/too many requests/i.test(txt)){last=new Error('RATE_LIMIT');if(i<tries){await sleep(2000*i);continue}throw last}if(!r.ok)throw new Error('HTTP_'+r.status);return JSON.parse(txt)}catch(e){clearTimeout(t);last=e?.name==='AbortError'?new Error('TIMEOUT'):e;if(i<tries)await sleep(1200*i)}}throw last||new Error('DATA_FETCH_FAILED')}
async function chart(v,range='1y',interval='1d'){const s=ticker(v);if(!s)throw Error('Invalid ticker');const k=`c:${s}:${range}:${interval}`,old=get(k);if(old)return old;const j=await yf(`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(s)}?range=${range}&interval=${interval}&events=div%2Csplits`),r=j?.chart?.result?.[0];if(!r)throw Error('No market data found');const q=r.indicators?.quote?.[0]||{},a=r.indicators?.adjclose?.[0]?.adjclose||[],o={ticker:s,currency:r.meta?.currency||'INR',exchange:r.meta?.exchangeName||'',regularMarketPrice:r.meta?.regularMarketPrice??null,timestamps:r.timestamp||[],open:q.open||[],high:q.high||[],low:q.low||[],close:q.close||[],volume:q.volume||[],adjclose:a};set(k,o);return o}
async function summary(v){const s=ticker(v),k=`s:${s}`,old=get(k);if(old)return old;const c=await chart(s),cl=c.close.filter(Number.isFinite),hi=c.high.filter(Number.isFinite),lo=c.low.filter(Number.isFinite),vo=c.volume.filter(Number.isFinite);const o={symbol:s,price:c.regularMarketPrice??cl.at(-1)??null,currency:c.currency,exchange:c.exchange,previousClose:cl.at(-2)??null,fiftyTwoWeekHigh:hi.length?Math.max(...hi):null,fiftyTwoWeekLow:lo.length?Math.min(...lo):null,averageVolume:vo.length?vo.reduce((a,b)=>a+b,0)/vo.length:null,volume:vo.at(-1)??null,chart:c,fundamentals:{note:'Full fundamentals require a reliable fundamentals provider; do not infer missing ROE, debt, margins, promoter or cash-flow values.'}};set(k,o);return o}
async function news(q){q=String(q||'').trim();if(!q)throw Error('query required');const k='n:'+q.toLowerCase(),old=get(k);if(old)return old;const j=await yf(`https://query1.finance.yahoo.com/v1/finance/search?q=${encodeURIComponent(q)}&newsCount=10&quotesCount=5`),a=(j?.news||[]).map(n=>({title:n.title||'',publisher:n.publisher||'',link:n.link||n.url||'#',publishedAt:n.providerPublishTime?new Date(n.providerPublishTime*1000).toISOString():''}));set(k,a);return a}
async function scan(limit=10){const ss=['RELIANCE','TCS','HDFCBANK','ICICIBANK','INFY','ITC','LT','BHARTIARTL','AXISBANK','MARUTI','SUNPHARMA','M&M','TITAN','BAJFINANCE','KOTAKBANK'].slice(0,Math.max(1,Math.min(Number(limit)||10,15))),out=[];for(const s of ss)try{const c=await chart(s,'6mo','1d'),cl=c.close.filter(Number.isFinite);if(cl.length<30)continue;const last=cl.at(-1),prev=cl.at(-2),s20=cl.slice(-20).reduce((a,b)=>a+b,0)/20,s50=cl.length>=50?cl.slice(-50).reduce((a,b)=>a+b,0)/50:null;out.push({symbol:c.ticker,price:last,momentumPct:prev?((last-prev)/prev)*100:0,sma20:s20,sma50:s50,trend:s50?(last>s20&&s20>s50?'BULLISH':last<s20&&s20<s50?'BEARISH':'MIXED'):(last>s20?'BULLISH':'BEARISH')})}catch{}return out}
export default async function handler(req,res){cors(res);if(req.method==='OPTIONS')return res.status(204).end();if(req.method!=='POST')return send(res,405,{error:'POST only'});const ip=req.headers['x-forwarded-for']?.split(',')[0]?.trim()||'unknown',rate=isRateLimited(ip);if(rate.limited)return send(res,429,{error:'Rate limit exceeded',resetAt:rate.resetAt});try{const b=typeof req.body==='string'?JSON.parse(req.body):(req.body||{});if(!b.type)return send(res,400,{error:'type required: summary|chart|news|scan'});if(b.type==='summary')return send(res,200,await summary(b.ticker));if(b.type==='chart')return send(res,200,await chart(b.ticker,b.range||'1y',b.interval||'1d'));if(b.type==='news')return send(res,200,await news(b.query||b.ticker));if(b.type==='scan')return send(res,200,await scan(b.limit));return send(res,400,{error:'Unknown type'})}catch(e){return send(res,500,{error:e.message||'Backend error'})}}
